# Generated by Django 4.2.8 on 2023-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cartaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
