# Generated by Django 4.2.8 on 2023-12-07 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='AuctionItem',
        ),
        migrations.RenameModel(
            old_name='Feature',
            new_name='AuctionItemFeature',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='AuctionItemReview',
        ),
        migrations.RenameModel(
            old_name='UpdateOrder',
            new_name='OrderUpdate',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Purchase',
        ),
        migrations.RenameModel(
            old_name='CheckoutDetail',
            new_name='PurchaseDetail',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='PurchaseItem',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='UserAccount',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='UserContact',
        ),
    ]
