# Generated by Django 4.2.8 on 2023-12-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='added_items',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='users.auctionitem'),
        ),
    ]
